= Community

++++
<div class="banner px-3 px-md-5">
    <div class="container text-left">
        <h2 class="pt-5">Community</h2>
        <p class="lead pt-3 text-white">Part of our team is strongly involved in open source software foundation.</p>
    </div>
</div>

<div class="container section px-3 px-md-5">
    <div class="section-content pt-5">
        <div class="row">
            <div class="align-self-center col community-logo">
                <img src="/images/asf-feather.svg">
            </div>
            <div class="align-self-center col">
                <h3>Apache Software Foundation</h3>
            </div>
        </div>
        <p class="lead">Apache committed contributor and member</p>
        <blockquote class="blockquote">
          <p class="mb-0 font-italic">The ASF develops, shepherds, and incubates hundreds of freely-available, enterprise-grade projects that serve as the backbone for some of
            the most visible and widely used applications in computing today. Through the ASF's merit-based process known as "The Apache Way,"
            more than 800 individual volunteer Members and 7,800+ code Committers across six continents successfully collaborate on innovations
            in Artificial Intelligence and Deep Learning, Big Data, Build Management, Cloud Computing, Content Management, DevOps, IoT and Edge Computing,
            Mobile, Servers, and Web Frameworks, among other categories.</p>
        </blockquote>
        <p><a href="https://www.apache.org/" target="_blank" title="ASF">Visit</a></p>
    </div>
</div>
++++
