= Yupiik Fusion 1.0.5 Released
:minisite-blog-published-date: 2023-07-19
:minisite-blog-categories: Release
:minisite-blog-authors: Francois Papon
:minisite-blog-summary: The Yupiik Fusion 1.0.5 has been released!

[abstract]
On behalf the Yupiik OSS team and other contributors, I'm happy to announce that Yupiik Fusion 1.0.5 has been released.
The artifacts are available on Maven Central and on the GitHub project page.

== What's new?

* [persistence] adding contextless Database (explicit connection parameter).
* [jwt] support list in Jwt.claim().
* [processor] handle optional imports for generated modules.
* [graalvm] generate resources.json and native-image.properties to include fusion json metadata (openrpc endpoint).
* [http-server] Enable to deploy a monitoring server by configuration, ensure request is completed even if completionstage does not return but fails.
* [jsonrpc] jsonrpc uses List and not array for serialization.
* [json] better enum support and jsonschema integration, tolerate to pass Map as a synonym of Object for generic mapping.

This release include fixes and improvements, more details are available here:

https://github.com/yupiik/fusion/releases/tag/fusion-1.0.5

The documentation is up-to-date here:

https://www.yupiik.io/fusion/

== How to start?

You can start be reading the link:https://www.yupiik.io/fusion/fusion/index.html[Getting Started page].

== Feedback are welcome
You can contribute, report bug or ask for improvement in the link:https://github.com/yupiik/fusion/issues[GitHub issue page]

Enjoy!
