= Yupiik Fusion 1.0.4 Released
:minisite-blog-published-date: 2023-06-28
:minisite-blog-categories: Release
:minisite-blog-authors: Francois Papon
:minisite-blog-summary: The Yupiik Fusion 1.0.4 has been released!

[abstract]
On behalf the Yupiik OSS team and other contributors, I'm happy to announce that Yupiik Fusion 1.0.4 has been released.
The artifacts are available on Maven Central and on the GitHub project page.

== What's new?

* New module *fusion-jwt* to parse and validate a JWT just using *fusion-json* dependency and the JVM
* Improve datasource rollback on sqlexception errors
* Many improvement in the *fusion-handlebars* templating module
* Add Body API in *fusion-http-server* module to easily manage request body usage through the java api Flow
* Upgrade to Apache Tomcat 10.1.10
* Make the configuration of the K8S http client more easy
* Tracing and logging improvement

This release include fixes and improvements, more details are available here:

https://github.com/yupiik/fusion/releases/tag/fusion-1.0.4

The documentation is up-to-date here:

https://www.yupiik.io/fusion/

== How to start?

You can start be reading the link:https://www.yupiik.io/fusion/fusion/index.html[Getting Started page].

== Feedback are welcome
You can contribute, report bug or ask for improvement in the link:https://github.com/yupiik/fusion/issues[GitHub issue page]

Enjoy!
