= Yupiik Fusion 1.0.8 Released
:minisite-blog-published-date: 2023-09-26
:minisite-blog-categories: Release
:minisite-blog-authors: Francois Papon
:minisite-blog-summary: The Yupiik Fusion 1.0.8 has been released!

[abstract]
On behalf the Yupiik OSS team and other contributors, I'm happy to announce that Yupiik Fusion 1.0.8 has been released.
The artifacts are available on Maven Central and on the GitHub project page.

== What's new?

* [dependencies] Upgrade to Apache Tomcat 10.1.13.
* [httpclient] basic rate limiting support.
* [subclassing] tolerate class templates/generics at some point.
* [k8s-operator] adding kubernetes-operator-base module.
* [kubernetes operator base] handle bookmark events.
* [zipkin] Ensure span tags are only strings since it would require a mapping step otherwise.
* [handlebars] better item template handling for each loop.
* [processor] Add support for Enum fields.

This release include fixes and improvements, more details are available here:

https://github.com/yupiik/fusion/releases/tag/fusion-1.0.8

The documentation is up-to-date here:

https://www.yupiik.io/fusion/

== How to start?

You can start be reading the link:https://www.yupiik.io/fusion/fusion/index.html[Getting Started page].

== Feedback are welcome
You can contribute, report bug or ask for improvement in the link:https://github.com/yupiik/fusion/issues[GitHub issue page]

Enjoy!
